import os

translations = {
    "Real Solutions. Real Impact.": "Echte Lösungen. Echte Wirkung.",
    "Explore how we apply systems engineering to solve industry-specific challenges with measurable results.": "Erfahren Sie, wie wir Systems Engineering anwenden, um branchenspezifische Herausforderungen mit messbaren Ergebnissen zu lösen.",
    
    "Smart Greenhouse Development": "Entwicklung eines intelligenten Gewächshauses",
    "<strong>Challenge:</strong> Utilization of multi disciplinar domains to develop a cost effective and robust smart Greenhouse system with cross-country teams.": "<strong>Herausforderung:</strong> Nutzung multidisziplinärer Bereiche zur Entwicklung eines kostengünstigen und robusten intelligenten Gewächshaussystems mit länderübergreifenden Teams.",
    "<strong>Solution:</strong> We developed an MBSE-driven smart greenhouse system integrating sensors, irrigation control, and light automation, ensuring optimal growing conditions.": "<strong>Lösung:</strong> Wir haben ein MBSE-gesteuertes intelligentes Gewächshaussystem entwickelt, das Sensoren, Bewässerungssteuerung und Lichtautomatisierung integriert und optimale Wachstumsbedingungen gewährleistet.",
    "<strong>Technologies Used:</strong> SysML, Arduino, IoT integration, V&amp;V strategy": "<strong>Verwendete Technologien:</strong> SysML, Arduino, IoT-Integration, V&amp;V-Strategie",
    "<strong>Impact:</strong> Increased yield stability by 30% and enabled remote management capabilities for urban growers.": "<strong>Auswirkung:</strong> Erhöhte Ertragsstabilität um 30 % und ermöglichte Fernverwaltungsfunktionen für städtische Züchter.",
    "Read full case study": "Vollständige Fallstudie lesen",
    "Case Study: MBSE-Driven Architecture for a Multi-Disciplinary Smart Greenhouse System": "Fallstudie: MBSE-gesteuerte Architektur für ein multidisziplinäres intelligentes Gewächshaussystem",
    "Executive Summary": "Zusammenfassung",
    "Developing modern, automated agricultural systems requires the seamless integration of hardware, software, and environmental science. A global client sought to build a cost-effective, robust, and automated smart greenhouse tailored for urban growers. Facing the challenge of coordinating cross-country engineering teams across multiple technical disciplines, they partnered with us to establish a rigorous, model-based system architecture from concept to prototype validation.": "Die Entwicklung moderner, automatisierter landwirtschaftlicher Systeme erfordert die nahtlose Integration von Hardware, Software und Umweltwissenschaften. Ein globaler Kunde wollte ein kostengünstiges, robustes und automatisiertes intelligentes Gewächshaus entwickeln, das auf städtische Züchter zugeschnitten ist. Angesichts der Herausforderung, länderübergreifende Engineering-Teams über mehrere technische Disziplinen hinweg zu koordinieren, arbeiteten sie mit uns zusammen, um eine strenge, modellbasierte Systemarchitektur vom Konzept bis zur Prototypenvalidierung zu etablieren.",
    "The Challenge: Cross-Domain &amp; Cross-Country Fragmentation": "Die Herausforderung: Domänen- &amp; länderübergreifende Fragmentierung",
    "Designing an IoT-enabled smart greenhouse demands tight synchronization between hardware structure, sensor integration, automated irrigation, and control software. The project faced two primary hurdles:": "Der Entwurf eines IoT-fähigen intelligenten Gewächshauses erfordert eine enge Synchronisierung zwischen Hardwarestruktur, Sensorintegration, automatisierter Bewässerung und Steuerungssoftware. Das Projekt stand vor zwei wesentlichen Hürden:",
    "<strong>Multi-Disciplinary Complexity:</strong> Bridging the gaps between agronomic needs, electronic hardware, and automated software algorithms.": "<strong>Multidisziplinäre Komplexität:</strong> Überbrückung der Lücken zwischen agronomischen Anforderungen, elektronischer Hardware und automatisierten Softwarealgorithmen.",
    "<strong>Geographical Dispersion:</strong> Aligning cross-country engineering teams to prevent design drifts, incompatible interfaces, and costly integration delays.": "<strong>Geografische Verteilung:</strong> Abstimmung länderübergreifender Engineering-Teams, um Designabweichungen, inkompatible Schnittstellen und kostspielige Integrationsverzögerungen zu vermeiden.",
    "Our Solution: End-to-End Systems Engineering &amp; MBSE": "Unsere Lösung: End-to-End Systems Engineering &amp; MBSE",
    "We acted as the foundational technical anchor, providing full Model-Based Systems Engineering (MBSE) and requirements engineering. This structured approach managed systemic complexity, allowing the client's internal teams to focus entirely on their core strengths: hardware production and software development.": "Wir fungierten als grundlegender technischer Anker und boten vollständiges Model-Based Systems Engineering (MBSE) und Requirements Engineering. Dieser strukturierte Ansatz bewältigte die systemische Komplexität und ermöglichte es den internen Teams des Kunden, sich ganz auf ihre Kernkompetenzen zu konzentrieren: Hardwareproduktion und Softwareentwicklung.",
    "1. Concept of Operations (ConOps) &amp; Capability Definition": "1. Concept of Operations (ConOps) &amp; Definition der Fähigkeiten",
    "We initiated the lifecycle by defining the Concept of Operations (ConOps) and mapping out operational scenarios for automated light, climate, and irrigation control. From these scenarios, we derived high-level system capabilities, establishing a clear, client-approved baseline before any engineering began.": "Wir leiteten den Lebenszyklus ein, indem wir das Concept of Operations (ConOps) definierten und Betriebsszenarien für automatisierte Licht-, Klima- und Bewässerungssteuerung ausarbeiteten. Aus diesen Szenarien leiteten wir übergeordnete Systemfähigkeiten ab und etablierten eine klare, vom Kunden genehmigte Basislinie, bevor die eigentliche Konstruktion begann.",
    "2. System Analysis &amp; Functional Layout": "2. Systemanalyse &amp; Funktionales Layout",
    "Utilizing SysML, we conducted a thorough system analysis to define core functions, logical interfaces, and the overall architectural layout. This step ensured all physical components and software blocks would integrate seamlessly.": "Mithilfe von SysML führten wir eine gründliche Systemanalyse durch, um Kernfunktionen, logische Schnittstellen und das gesamte Architekturlayout zu definieren. Dieser Schritt stellte sicher, dass alle physischen Komponenten und Softwareblöcke nahtlos integriert werden konnten.",
    
    "3. Requirements Cascade, Domain Allocation, &amp; EU Compliance": "3. Anforderungskaskade, Domänenzuordnung &amp; EU-Konformität",
    "To translate the architecture into actionable tasks for the engineering domains, we established a strict requirements hierarchy:": "Um die Architektur in umsetzbare Aufgaben für die Engineering-Domänen zu übersetzen, haben wir eine strenge Anforderungshierarchie etabliert:",
    "<strong>System-Level Requirements:</strong> Documented the overarching performance and environmental criteria.": "<strong>Anforderungen auf Systemebene:</strong> Dokumentierte die übergeordneten Leistungs- und Umweltkriterien.",
    "<strong>EU Regulatory Mapping:</strong> Directly linked system requirements to harmonized European standards to streamline future CE Certification paths (including Machine Safety and Radio Equipment directives).": "<strong>EU-Regulierungs-Mapping:</strong> Direkte Verknüpfung der Systemanforderungen mit harmonisierten europäischen Normen, um zukünftige CE-Zertifizierungswege (einschließlich Maschinenrichtlinie und Funkanlagenrichtlinie) zu rationalisieren.",
    "<strong>System Requirements Allocated to Software (SRATS):</strong> Defined precise parameters for the automated control algorithms.": "<strong>System Requirements Allocated to Software (SRATS):</strong> Definierte präzise Parameter für die automatisierten Steuerungsalgorithmen.",
    "<strong>Hardware Requirements Specification (HRS):</strong> Specified the sensor thresholds, power distribution, and component constraints.": "<strong>Hardware Requirements Specification (HRS):</strong> Spezifizierte die Sensorschwellenwerte, Energieverteilung und Komponenteneinschränkungen.",
    
    "4. Verification &amp; Validation (V&amp;V) Strategy": "4. Verifizierungs- &amp; Validierungsstrategie (V&amp;V)",
    "Parallel to requirements definition, we authored targeted Test Cases tied directly to the system requirements. This enabled rigorous validation during the assembly of Prototype 1, ensuring the integrated system met all functional and operational benchmarks.": "Parallel zur Anforderungsdefinition verfassten wir gezielte Testfälle, die direkt an die Systemanforderungen gebunden waren. Dies ermöglichte eine strenge Validierung während der Montage von Prototyp 1 und stellte sicher, dass das integrierte System alle funktionalen und operativen Benchmarks erfüllte.",
    
    "Technologies Used": "Verwendete Technologien",
    "<strong>Systems Engineering &amp; Modeling:</strong> SysML, Robust Requirements Engineering": "<strong>Systems Engineering &amp; Modellierung:</strong> SysML, Robustes Requirements Engineering",
    "<strong>Hardware &amp; IoT:</strong> Arduino prototyping, Sensor Integration (Climate, Moisture, Light Automation)": "<strong>Hardware &amp; IoT:</strong> Arduino-Prototyping, Sensorintegration (Klima-, Feuchtigkeits-, Lichtautomatisierung)",
    "<strong>Regulatory &amp; Compliance Strategy:</strong> CE Marking Alignment (Machinery Regulation 2023/1230, RED, EMC), ISO 14982 (Agricultural EMC standards verification)": "<strong>Regulierungs- &amp; Compliance-Strategie:</strong> Ausrichtung auf CE-Kennzeichnung (Maschinenverordnung 2023/1230, RED, EMV), ISO 14982 (Verifizierung landwirtschaftlicher EMV-Normen)",
    "<strong>Methodology:</strong> Full V&amp;V (Verification &amp; Validation) Strategy, ConOps-driven design": "<strong>Methodik:</strong> Vollständige V&amp;V-Strategie (Verifizierung &amp; Validierung), ConOps-gesteuertes Design",
    
    "The Impact: Accelerated Prototyping &amp; Enhanced Yield": "Die Auswirkung: Beschleunigtes Prototyping &amp; erhöhter Ertrag",
    "By decoupling system architecture from domain-level execution, we streamlined the development pipeline for the international team, delivering significant business and technical outcomes:": "Durch die Entkopplung der Systemarchitektur von der Ausführung auf Domänenebene haben wir die Entwicklungspipeline für das internationale Team rationalisiert und signifikante geschäftliche und technische Ergebnisse geliefert:",
    "<strong>30% Increase in Yield Stability:</strong> Precision automation algorithms ensured optimized, predictable growing conditions.": "<strong>30 % höhere Ertragsstabilität:</strong> Präzisionsautomatisierungsalgorithmen sorgten für optimierte, vorhersehbare Wachstumsbedingungen.",
    "<strong>Accelerated Path to EU Market Entry:</strong> By embedding CE compliance and agricultural equipment safety standards directly into the SysML model and test cases, we minimized regulatory redesign risks and shortened the timeline for market certification.": "<strong>Beschleunigter Weg zum EU-Markteintritt:</strong> Durch die direkte Einbettung der CE-Konformität und der Sicherheitsstandards für landwirtschaftliche Geräte in das SysML-Modell und die Testfälle minimierten wir regulatorische Redesign-Risiken und verkürzten den Zeitplan für die Marktzertifizierung.",
    "<strong>Seamless Global Collaboration:</strong> The SysML model acted as a single source of truth, eliminating cross-border design friction.": "<strong>Nahtlose globale Zusammenarbeit:</strong> Das SysML-Modell fungierte als Single Source of Truth und beseitigte grenzüberschreitende Designreibungen.",
    "<strong>Remote Management Ready:</strong> Successfully validated IoT capabilities, empowering urban growers with remote monitoring and control.": "<strong>Bereit für Fernverwaltung:</strong> Erfolgreich validierte IoT-Fähigkeiten, die städtischen Züchtern Fernüberwachung und -steuerung ermöglichen.",
    "<strong>Resource Optimization:</strong> Enabled the client to focus 100% of their engineering capacity on execution rather than architectural or regulatory troubleshooting.": "<strong>Ressourcenoptimierung:</strong> Ermöglichte es dem Kunden, 100 % seiner Engineering-Kapazität auf die Ausführung zu konzentrieren, anstatt auf architektonische oder regulatorische Fehlerbehebung.",
    
    "Capella Integration for UAV Manufacturer": "Capella-Integration für UAV-Hersteller",
    "<strong>Challenge:</strong> Fragmented product development process hindered scalability and cross-team alignment.": "<strong>Herausforderung:</strong> Fragmentierter Produktentwicklungsprozess behinderte Skalierbarkeit und teamübergreifende Abstimmung.",
    "<strong>Solution:</strong> We integrated the Capella MBSE tool into the UAV manufacturer's development pipeline, aligning requirements, architecture, and simulation models.": "<strong>Lösung:</strong> Wir haben das Capella MBSE-Tool in die Entwicklungspipeline des UAV-Herstellers integriert und Anforderungen, Architektur und Simulationsmodelle aufeinander abgestimmt.",
    "<strong>Technologies Used:</strong> Capella, Simulink, Polarion, MBSE process tailoring": "<strong>Verwendete Technologien:</strong> Capella, Simulink, Polarion, MBSE-Prozessanpassung",
    "<strong>Impact:</strong> Reduced design inconsistencies by 45% and improved traceability across engineering artifacts.": "<strong>Auswirkung:</strong> Reduzierte Designinkonsistenzen um 45 % und verbesserte Rückverfolgbarkeit über alle Engineering-Artefakte hinweg.",
    
    "Case Study: Optimizing UAV Development with Tailored Capella MBSE Integration": "Fallstudie: Optimierung der UAV-Entwicklung mit maßgeschneiderter Capella-MBSE-Integration",
    "A leading Unmanned Aerial Vehicle (UAV) manufacturer faced operational bottlenecks due to a fragmented product development process. As the engineering team scaled, a lack of cross-team alignment and disconnected engineering artifacts risked design inconsistencies. We successfully integrated the Capella MBSE (Model-Based Systems Engineering) tool into their development pipeline, harmonizing requirements, architecture, and models to ensure seamless scalability.": "Ein führender Hersteller von unbemannten Luftfahrzeugen (UAV) sah sich aufgrund eines fragmentierten Produktentwicklungsprozesses mit operativen Engpässen konfrontiert. Da das Engineering-Team wuchs, riskierten mangelnde teamübergreifende Abstimmung und nicht miteinander verbundene Engineering-Artefakte Designinkonsistenzen. Wir haben das Capella MBSE-Tool (Model-Based Systems Engineering) erfolgreich in deren Entwicklungspipeline integriert und Anforderungen, Architektur und Modelle harmonisiert, um eine nahtlose Skalierbarkeit zu gewährleisten.",
    
    "The Challenge: Disconnected Pipelines &amp; Scalability Bottlenecks": "Die Herausforderung: Unverbundene Pipelines &amp; Skalierbarkeitsengpässe",
    "In complex aerospace and defense engineering, alignment is everything. The client's existing product development lifecycle suffered from fragmentation. Without a unified source of truth, the team faced:": "In der komplexen Luft- und Raumfahrt- sowie Verteidigungstechnik ist die Abstimmung alles. Der bestehende Produktentwicklungslebenszyklus des Kunden litt unter Fragmentierung. Ohne eine einheitliche Datenquelle (Single Source of Truth) stand das Team vor folgenden Problemen:",
    "Siloed engineering artifacts across requirements and architectural models.": "Isolierte Engineering-Artefakte über Anforderungen und Architekturmodelle hinweg.",
    "Traceability leaks that risked design inconsistencies during rapid scaling.": "Lücken in der Rückverfolgbarkeit, die bei schneller Skalierung Designinkonsistenzen riskierten.",
    "Cross-team misalignment on complex system interfaces and workflows.": "Teamübergreifende Fehlalarme bei komplexen Systemschnittstellen und Workflows.",
    
    "Our Solution: A Strategic, Human-Centric MBSE Implementation": "Unsere Lösung: Eine strategische, menschenzentrierte MBSE-Implementierung",
    "Rather than just delivering tools, we engineered a comprehensive transformation process divided into three distinct phases:": "Anstatt nur Tools zu liefern, haben wir einen umfassenden Transformationsprozess entwickelt, der in drei verschiedene Phasen unterteilt ist:",
    "<strong>1. Capability Building &amp; Cultural Alignment</strong><br>": "<strong>1. Fähigkeitsaufbau &amp; Kulturelle Ausrichtung</strong><br>",
    "We initiated the project with targeted peer-to-peer lectures to establish a deep, shared understanding of the Capella modeling environment across the client's engineering teams, ensuring rapid tool adoption.": "Wir haben das Projekt mit gezielten Peer-to-Peer-Vorlesungen gestartet, um ein tiefes, gemeinsames Verständnis der Capella-Modellierungsumgebung in den Engineering-Teams des Kunden zu etablieren und so eine schnelle Tool-Einführung zu gewährleisten.",
    "<strong>2. Deep-Dive Gap Analysis</strong><br>": "<strong>2. Deep-Dive-Lückenanalyse</strong><br>",
    "We analyzed the client's existing \"way of working\" to identify critical process leaks, trace pathway gaps, and architectural inconsistencies.": "Wir analysierten die bestehende „Arbeitsweise“ des Kunden, um kritische Prozesslecks, Lücken in den Rückverfolgungspfaden und architektonische Inkonsistenzen zu identifizieren.",
    "<strong>3. Tailored Workflow Engineering &amp; Automation</strong><br>": "<strong>3. Maßgeschneidertes Workflow-Engineering &amp; Automatisierung</strong><br>",
    "After mapping the gaps, we presented a matrix of strategic solutions. The client selected a preferred path focused on deep pipeline integration:": "Nach der Kartierung der Lücken präsentierten wir eine Matrix strategischer Lösungen. Der Kunde wählte einen bevorzugten Weg, der sich auf eine tiefe Pipeline-Integration konzentrierte:",
    
    "<strong>Unified Lifecycle Management:</strong> Coordinated the implementation of robust configuration and documentation management workflows.": "<strong>Unified Lifecycle Management:</strong> Koordinierung der Implementierung robuster Workflows für das Konfigurations- und Dokumentationsmanagement.",
    "<strong>Toolchain Synchronization:</strong> Integrated Capella with Jira and Git, ensuring models, requirements, and tasks evolve in lockstep.": "<strong>Toolchain-Synchronisation:</strong> Capella in Jira und Git integriert, um sicherzustellen, dass sich Modelle, Anforderungen und Aufgaben im Gleichschritt entwickeln.",
    "<strong>Process Tailoring &amp; Automation:</strong> Developed targeted automation scripts to streamline data exchange, drastically reducing manual engineering overhead.": "<strong>Prozessanpassung &amp; Automatisierung:</strong> Entwicklung zielgerichteter Automatisierungsskripte zur Rationalisierung des Datenaustauschs, wodurch der manuelle Engineering-Aufwand drastisch reduziert wurde.",
    
    "<strong>MBSE Environment:</strong> Capella": "<strong>MBSE-Umgebung:</strong> Capella",
    "<strong>Lifecycle &amp; Version Control:</strong> Git, Jira": "<strong>Lifecycle &amp; Versionskontrolle:</strong> Git, Jira",
    "<strong>Methodology:</strong> Custom MBSE process tailoring &amp; automation": "<strong>Methodik:</strong> Maßgeschneiderte MBSE-Prozessanpassung &amp; Automatisierung",
    
    "The Impact: A Single Source of Truth": "Die Auswirkung: Eine Single Source of Truth",
    "The integration of Capella transformed the client's engineering culture from document-centric to model-based, delivering measurable operational improvements:": "Die Integration von Capella transformierte die Engineering-Kultur des Kunden von einer dokumenten- zu einer modellbasierten, was messbare betriebliche Verbesserungen brachte:",
    "<strong>Eliminated Design Inconsistencies:</strong> Bridged the gap between high-level requirements and physical architecture.": "<strong>Beseitigung von Designinkonsistenzen:</strong> Überbrückung der Lücke zwischen übergeordneten Anforderungen und physischer Architektur.",
    "<strong>End-to-End Traceability:</strong> Established clear, unbroken trace pathways across all engineering artifacts.": "<strong>End-to-End-Rückverfolgbarkeit:</strong> Etablierung klarer, ununterbrochener Rückverfolgungspfade über alle Engineering-Artefakte hinweg.",
    "<strong>Future-Proof Scalability:</strong> Equipped the development team with a repeatable, automated pipeline ready to handle next-generation UAV variants.": "<strong>Zukunftssichere Skalierbarkeit:</strong> Ausrüstung des Entwicklungsteams mit einer wiederholbaren, automatisierten Pipeline, die bereit ist, UAV-Varianten der nächsten Generation zu handhaben.",
    
    "Ready to transform your system development?": "Bereit, Ihre Systementwicklung zu transformieren?",
    "Get in touch with us today →": "Kontaktieren Sie uns noch heute →"
}

with open('use-cases_DE.html', 'r', encoding='utf-8') as f:
    content = f.read()

for eng, ger in translations.items():
    content = content.replace(eng, ger)

with open('use-cases_DE.html', 'w', encoding='utf-8') as f:
    f.write(content)
print("use-cases_DE.html translated")
